version: "3.8"
services:
  database:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: public
    ports:
      - "3306:3306"
    volumes:
      - ./.data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  